### ISSUE TITLE
Error messages when trying to compile basic

### ISSUE THREAD

**Issue by k1333712** [mgi2212/Thunderbolt#1]
Hi,
I am attempting to use the library you have kindly shared to make a basic clock. I have tried running the basic.ino code you supplied but cannot seem to get it to work. I get the following error message when trying to load to my Arduino Due,

basic.ino: In function 'void displayTime(GPSTime)':
basic:42: error: 'struct GPSTime' has no member named 'hours'
basic:42: error: 'struct GPSTime' has no member named 'minutes'
basic:42: error: 'struct GPSTime' has no member named 'seconds'
'struct GPSTime' has no member named 'hours'

apologies if this is a really simple issue but I have limited experience with coding.

**Comment by mgi2212** [comment]
Hello,

I suspect that the compiler can’t find the library.  Did you install the library using the .zip file downloaded from github?  Feel free to reach out to me on email direct at danq@quigleys.usmailto:danq@quigleys.us.

Best,

Dan

**Comment by Bugs-find-me** [comment]
I had this same problem.  The GPSTime struct uses .Hour .Minute and .Second not .hours .minutes .seconds.  Change those 3 lines and it will compile.
